import type { ChallengeDefinition } from './types.js';

export const seededChallenges: ChallengeDefinition[] = [
  {
    id: 'T1-ASK-01',
    title: 'Write a Clear Prompt Brief',
    category: 'asking effective questions',
    difficulty: 'tier_1',
    summary: 'Draft a concise request that includes goal, audience, and constraints.',
    fullDescription:
      'Write one message to the tutor agent asking for help on a lesson. Include the user goal, who the answer is for, and at least one concrete constraint.',
    learningGoals: ['Use explicit goals', 'Constrain scope', 'Improve prompt clarity'],
    recommendedAgentTypes: ['coach'],
    requiredSkills: [],
    optionalSkills: ['Plan Writer'],
    inputAssets: [],
    hints: [
      'Use a structure like: Goal -> Audience -> Constraints.',
      'Include at least one hard constraint such as output length or format.',
      'State what success looks like in a single sentence.',
    ],
    successCriteria: [
      'Mentions a clear goal.',
      'Mentions an audience.',
      'Mentions one or more constraints.',
    ],
    validation: {
      type: 'keyword',
      mode: 'all',
      keywords: ['goal', 'audience', 'constraint'],
    },
    completionLesson: {
      whatYouLearned: 'Clear prompts improve answer quality and reduce back-and-forth.',
      nextMission: 'Try a skill-first challenge and ask the agent to use a specific tool.',
    },
    unlockRequirements: [],
  },
  {
    id: 'T1-OBS-02',
    title: 'Observe Agent Status Correctly',
    category: 'basic reasoning',
    difficulty: 'tier_1',
    summary: 'Read the Agent Dock and report who is blocked.',
    fullDescription:
      'Inspect the Agent Dock and answer with exactly one sentence that identifies the blocked agent and their specialty.',
    learningGoals: ['Read UI state accurately', 'Return precise observations'],
    recommendedAgentTypes: ['assistant'],
    requiredSkills: [],
    optionalSkills: [],
    inputAssets: ['Agent Dock panel'],
    hints: [
      'Only one agent has a blocked status badge.',
      'Include both the name and specialty in one sentence.',
    ],
    successCriteria: ['Must identify Verifier as blocked.', 'Must mention QA and regression checks.'],
    validation: {
      type: 'keyword',
      mode: 'all',
      keywords: ['verifier', 'qa', 'regression'],
    },
    completionLesson: {
      whatYouLearned: 'Grounding responses in observed UI data prevents hallucination.',
      nextMission: 'Summarize a short thread using explicit status/action language.',
    },
    unlockRequirements: [],
  },
  {
    id: 'T1-SUM-03',
    title: 'Summarize a Thread in 3 Signals',
    category: 'summarization',
    difficulty: 'tier_1',
    summary: 'Summarize conversation state with blocker, next step, and owner.',
    fullDescription:
      'Write a short summary of the Chat + Skills conversation that includes one blocker/risk, one next step, and one owner.',
    learningGoals: ['Produce concise summaries', 'Extract action-oriented signal'],
    recommendedAgentTypes: ['coach'],
    requiredSkills: [],
    optionalSkills: ['Repo Search'],
    inputAssets: ['Chat + Skills panel'],
    hints: [
      'Use three clauses: blocker, next step, owner.',
      'Name at least one panel module from the conversation.',
    ],
    successCriteria: ['Contains blocker or risk', 'Contains next step', 'Contains owner'],
    validation: {
      type: 'keyword',
      mode: 'all',
      keywords: ['block', 'next step', 'owner'],
    },
    completionLesson: {
      whatYouLearned: 'Compact status summaries make handoffs faster and less ambiguous.',
      nextMission: 'Move to a Tier 2 challenge and use one skill intentionally.',
    },
    unlockRequirements: [],
  },
  {
    id: 'T1-PLN-04',
    title: 'Plan a Single Next Action',
    category: 'planning',
    difficulty: 'tier_1',
    summary: 'Define one concrete action with command and expected output.',
    fullDescription:
      'Provide one execution step for this project. Include the command to run and what result you expect to verify.',
    learningGoals: ['Create executable next steps', 'Make validation explicit'],
    recommendedAgentTypes: ['builder'],
    requiredSkills: [],
    optionalSkills: ['Repo Search'],
    inputAssets: ['Repository workspace'],
    hints: [
      'A complete step includes action + validation.',
      'Use script names from package.json for realism.',
    ],
    successCriteria: ['Mentions a command', 'Mentions expected verification output'],
    validation: {
      type: 'keyword',
      mode: 'all',
      keywords: ['npm run', 'expect'],
    },
    completionLesson: {
      whatYouLearned: 'Explicit verification criteria reduce rework and confusion.',
      nextMission: 'Use a single skill to inspect files and report findings.',
    },
    unlockRequirements: ['T1-ASK-01'],
  },
  {
    id: 'T2-SKL-05',
    title: 'Use a File Reading Skill',
    category: 'reading files',
    difficulty: 'tier_2',
    summary: 'Identify where challenge content is stored and how to run checks.',
    fullDescription:
      'Assume you used a file-reading skill to inspect docs. Report the challenge content location and the all-in-one verification command.',
    learningGoals: ['Use skill output in answers', 'Locate project structure quickly'],
    recommendedAgentTypes: ['builder'],
    requiredSkills: ['Repo Search'],
    optionalSkills: ['Plan Writer'],
    inputAssets: ['README.md', 'src/challenges'],
    hints: [
      'Challenge content is under src/challenges.',
      'The project has a check script that chains lint, test, and build.',
    ],
    successCriteria: ['Mentions src/challenges', 'Mentions npm run check'],
    validation: {
      type: 'keyword',
      mode: 'all',
      keywords: ['src/challenges', 'npm run check'],
    },
    completionLesson: {
      whatYouLearned: 'Skill-assisted file lookup speeds up repo orientation.',
      nextMission: 'Try JSON-formatted outputs for repeatable tool requests.',
    },
    unlockRequirements: ['T1-SUM-03'],
  },
  {
    id: 'T2-RSR-06',
    title: 'Request Skill Use as JSON',
    category: 'research',
    difficulty: 'tier_2',
    summary: 'Respond in JSON with tool, query, and reason fields.',
    fullDescription:
      'Return a JSON object that asks the assistant to run a repo search for challenge validation logic. Include keys tool, query, and reason.',
    learningGoals: ['Use structured outputs', 'Make tool intent auditable'],
    recommendedAgentTypes: ['scout'],
    requiredSkills: ['Repo Search'],
    optionalSkills: [],
    inputAssets: ['src/challenges/validation.ts'],
    hints: [
      'The response must be valid JSON, not prose.',
      'Use a query that includes the word validation.',
      'Keep reason short and specific.',
    ],
    successCriteria: ['JSON parses successfully', 'Contains tool/query/reason keys'],
    validation: {
      type: 'json',
      requiredKeys: ['tool', 'query', 'reason'],
      expectedValues: {
        tool: 'repo_search',
      },
    },
    completionLesson: {
      whatYouLearned: 'Structured requests are easier to automate and evaluate.',
      nextMission: 'Inspect UI rendering paths and map them to module files.',
    },
    unlockRequirements: ['T2-SKL-05'],
  },
  {
    id: 'T2-COD-07',
    title: 'Inspect the Challenge Board Renderer',
    category: 'code inspection',
    difficulty: 'tier_2',
    summary: 'Identify which file renders the challenge board and list two artifacts it renders.',
    fullDescription:
      'Answer with one sentence that names the source file for challenge board rendering and at least two UI artifacts it outputs.',
    learningGoals: ['Trace rendering ownership', 'Read code for concrete outputs'],
    recommendedAgentTypes: ['builder'],
    requiredSkills: ['Repo Search'],
    optionalSkills: ['QA Handoff'],
    inputAssets: ['src/ui/shell.ts'],
    hints: [
      'The board panel is in src/ui/shell.ts.',
      'Artifacts include challenge list, hints, success criteria, and lesson summary.',
    ],
    successCriteria: ['Names src/ui/shell.ts', 'Mentions at least two rendered artifacts'],
    validation: {
      type: 'keyword',
      mode: 'all',
      keywords: ['src/ui/shell.ts', 'challenge', 'hint'],
    },
    completionLesson: {
      whatYouLearned: 'Knowing render ownership helps you patch UI behavior safely.',
      nextMission: 'Run a debugging-style report with issue, command, and fix fields.',
    },
    unlockRequirements: ['T2-RSR-06'],
  },
  {
    id: 'T2-DBG-08',
    title: 'Draft a Deterministic Debug Report',
    category: 'debugging',
    difficulty: 'tier_2',
    summary: 'Produce JSON with issue, command, and fix for a failing check.',
    fullDescription:
      'Return JSON describing a hypothetical failing quality gate. Include keys issue, command, and fix. Keep each value concise.',
    learningGoals: ['Report failures reproducibly', 'Separate symptom from remediation'],
    recommendedAgentTypes: ['verifier'],
    requiredSkills: ['Repo Search'],
    optionalSkills: ['QA Handoff'],
    inputAssets: ['package.json scripts'],
    hints: [
      'Use npm run check as the command unless you have a narrower scope.',
      'The fix should be an action, not just a diagnosis.',
    ],
    successCriteria: ['JSON parses', 'Contains issue/command/fix keys'],
    validation: {
      type: 'json',
      requiredKeys: ['issue', 'command', 'fix'],
    },
    completionLesson: {
      whatYouLearned: 'Deterministic debug reports make QA handoff faster and measurable.',
      nextMission: 'You are ready for Tier 3 context-heavy challenges.',
    },
    unlockRequirements: ['T2-COD-07'],
  },
];
